### t.stack

In [1]:
import torch as t

x = t.Tensor([1,2,3])
y = t.Tensor([4,5,6])
t.stack([x,y], dim=-1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

### t.clamp

In [2]:
import torch as t

x = t.Tensor([1, 2, 3, 4, 5, 6])
t.clamp(x, min=1, max=5)


tensor([1., 2., 3., 4., 5., 5.])

### t.unsqueeze

In [5]:
import torch as t
x = t.Tensor([[1], [2], [3]])
print(x.size())
x = x.unsqueeze(2)
print(x.size())
x = x.expand(3, 1, 1) 
print(x.size())

torch.Size([3, 1])
torch.Size([3, 1, 1])
torch.Size([3, 1, 1])


### t.gather

 在dim维度上，按照indexs所给的坐标选择元素，
 返回一个和indexs维度相同大小的tensor。

In [11]:
import torch as t
import torch as t
x = t.Tensor([[1], [2], [3]])
print(x.size())
inds = t.tensor([[0],[1]])
print(inds.size())
y = x.gather(0, inds)
print(y)
print(y.size())

torch.Size([3, 1])
torch.Size([2, 1])
tensor([[1.],
        [2.]])
torch.Size([2, 1])


## Softmax

In [2]:
import torch as t
import torch.nn as nn

y = t.randn(2)
print('y 模拟两个神经元的输出：', y)

m = nn.Softmax(dim=0)
out = m(y)
print('经过激活函数之后：', out)
print('和为：', t.sum(out))

y 模拟两个神经元的输出： tensor([ 0.5111, -0.0766])
经过激活函数之后： tensor([0.6428, 0.3572])
和为： tensor(1.)


In [5]:
import torch as t
import torch.nn as nn

x = t.randint(0, 255, (1, 128 * 128), dtype=t.float32)

# 全连接
fc = nn.Linear(128 * 128, 2)
y = fc(x)
print(y)

# 激活函数
output  = nn.Softmax(dim=1)(y)
print(output)

tensor([[28.3384, 35.5969]], grad_fn=<AddmmBackward0>)
tensor([[7.0364e-04, 9.9930e-01]], grad_fn=<SoftmaxBackward0>)
